# Generated by Django 5.0.1 on 2024-02-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('dimension', models.IntegerField()),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
