# Generated by Django 5.0.1 on 2024-02-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.CharField(max_length=100),
        ),
    ]
